trigger:
  branches:
    include:
      - main   # or 'master' if that's your default branch

variables:
  azureWebAppPublishProfile: >
    <?xml version="1.0" encoding="utf-8"?>
    <publishData>
      <publishProfile profileName="smartclinic - Web Deploy" 
                      publishMethod="MSDeploy"
                      publishUrl="smartclinic-bqhhejhud9a0ahba.scm.canadacentral-01.azurewebsites.net:443" 
                      msdeploySite="smartclinic"
                      userName="$smartclinic" 
                      userPWD="Xcp5cAYRgdCAKspp1jAdWexSzkLjjdNHgtHt9Rt3sBeAMLBvbZ2gRDWff1MT"
                      destinationAppUrl="http://smartclinic-bqhhejhud9a0ahba.canadacentral-01.azurewebsites.net"
                      SQLServerDBConnectionString=""
                      mySQLDBConnectionString=""
                      hostingProviderForumLink=""
                      controlPanelLink="https://portal.azure.com"
                      webSystem="WebSites" />
    </publishData>

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Use Node.js'

  - script: |
      npm install
      npm run build   # remove this line if you don't have a build step
    displayName: 'Install dependencies and build'

  - task: AzureWebApp@1
    inputs:
      appType: 'webApp'
      azureSubscription: ''  # leave blank if using publish profile
      appName: 'smartclinic-backend'
      package: '$(System.DefaultWorkingDirectory)'
      deploymentMethod: 'auto'
      enableCustomDeployment: true
      usePublishProfile: true
      publishProfile: '$(azureWebAppPublishProfile)'
